export const LANGUAGES = [
	'Afrikaans',
	'Arabic',
	'Armenian',
	'Azerbaijani',
	'Belarusian',
	'Bosnian',
	'Bulgarian',
	'Catalan',
	'Chinese',
	'Croatian',
	'Czech',
	'Danish',
	'Dutch',
	'English',
	'Estonian',
	'Finnish',
	'French',
	'Galician',
	'German',
	'Greek',
	'Hebrew',
	'Hindi',
	'Hungarian',
	'Icelandic',
	'Indonesian',
	'Italian',
	'Japanese',
	'Kannada',
	'Kazakh',
	'Korean',
	'Latvian',
	'Lithuanian',
	'Macedonian',
	'Malay',
	'Marathi',
	'Maori',
	'Nepali',
	'Norwegian',
	'Persian',
	'Polish',
	'Portuguese',
	'Romanian',
	'Russian',
	'Serbian',
	'Slovak',
	'Slovenian',
	'Spanish',
	'Swahili',
	'Swedish',
	'Tagalog',
	'Tamil',
	'Thai',
	'Turkish',
	'Ukrainian',
	'Urdu',
	'Vietnamese',
	'Welsh',
] as const;

export type SupportedLanguage = (typeof LANGUAGES)[number];

// Mapping of language names to country codes for flag display
export const LANGUAGE_TO_FLAG: Record<string, string> = {
	Afrikaans: 'ZA',
	Arabic: 'SA',
	Armenian: 'AM',
	Azerbaijani: 'AZ',
	Belarusian: 'BY',
	Bosnian: 'BA',
	Bulgarian: 'BG',
	Catalan: 'ES',
	Chinese: 'CN',
	Croatian: 'HR',
	Czech: 'CZ',
	Danish: 'DK',
	Dutch: 'NL',
	English: 'US',
	Estonian: 'EE',
	Finnish: 'FI',
	French: 'FR',
	Galician: 'ES',
	German: 'DE',
	Greek: 'GR',
	Hebrew: 'IL',
	Hindi: 'IN',
	Hungarian: 'HU',
	Icelandic: 'IS',
	Indonesian: 'ID',
	Italian: 'IT',
	Japanese: 'JP',
	Kannada: 'IN',
	Kazakh: 'KZ',
	Korean: 'KR',
	Latvian: 'LV',
	Lithuanian: 'LT',
	Macedonian: 'MK',
	Malay: 'MY',
	Marathi: 'IN',
	Maori: 'NZ',
	Nepali: 'NP',
	Norwegian: 'NO',
	Persian: 'IR',
	Polish: 'PL',
	Portuguese: 'PT',
	Romanian: 'RO',
	Russian: 'RU',
	Serbian: 'RS',
	Slovak: 'SK',
	Slovenian: 'SI',
	Spanish: 'ES',
	Swahili: 'KE',
	Swedish: 'SE',
	Tagalog: 'PH',
	Tamil: 'LK',
	Thai: 'TH',
	Turkish: 'TR',
	Ukrainian: 'UA',
	Urdu: 'PK',
	Vietnamese: 'VN',
	Welsh: 'GB-WLS',
};
